---
name: Checks
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4 # Updated to the latest version
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Updated to the latest version
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: Build Docker Image
      #   run: docker-compose build app
      
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
        
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"